import { addTypeTemplate, useNuxt } from '@nuxt/kit';

export function registerTemplates(resolve: (...p: string[]) => string, nuxt = useNuxt()) {
  // const isDev = !!(nuxt.options.dev || nuxt.options._prepare);

  addTypeTemplate({
    filename: 'modules/nuxt-box-typescript-sdk.d.ts',
    getContents: () => `// Auto-Generated by 'nuxt-box-typescript-sdk'
import { AccessToken } from 'box-typescript-sdk-gen/lib/schemas/accessToken.generated.js';
import { GetAuthorizeUrlOptions } from 'box-typescript-sdk-gen/lib/box/oauth.generated.js';

declare module "nitropack" {
  interface NitroRuntimeHooks {
    "box:login:before": (options?: GetAuthorizeUrlOptions) => void | Promise<void>;
    "box:login:success": (response: AccessToken) => void | Promise<void>;
    "box:token:storageKey": (ctx: { key: string, auth: 'ccg' | 'jwt' | 'oauth' }) => void | Promise<void>;
  }
}

export {};
`
  });
}
