import { addTypeTemplate, useNuxt } from '@nuxt/kit';

export function registerTemplates(resolve: (...p: string[]) => string, nuxt = useNuxt()) {
  // const isDev = !!(nuxt.options.dev || nuxt.options._prepare);

  addTypeTemplate({
    filename: 'modules/nuxt-box-typescript-sdk.d.ts',
    getContents: () => `// Auto-Generated by 'nuxt-box-typescript-sdk'
import { H3Event } from 'h3';
import { AccessToken } from 'box-typescript-sdk-gen/lib/schemas/accessToken.generated.js';
import { GetAuthorizeUrlOptions } from 'box-typescript-sdk-gen/lib/box/oauth.generated.js';

declare module "nitropack" {
  interface NitroRuntimeHooks {
    "box:login:before": (ctx: { event: H3Event, options?: GetAuthorizeUrlOptions }) => void | Promise<void>;
    "box:login:success": (ctx: { event: H3Event, response: AccessToken }) => void | Promise<void>;
    "box:token:storageKey": (ctx: { event: H3Event, data: { key: string, auth: 'ccg' | 'jwt' | 'oauth' } }) => void | Promise<void>;
  }
}

export {};
`
  });
}
